//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRI_STORE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRI_STORE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11228 {
            get {
                object obj = ResourceManager.GetObject("11228", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _15 {
            get {
                object obj = ResourceManager.GetObject("15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9fb4711a395c88d_file_0000000039a862438389c81bb8fd8697_wm {
            get {
                object obj = ResourceManager.GetObject("9fb4711a395c88d_file_0000000039a862438389c81bb8fd8697_wm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bab {
            get {
                object obj = ResourceManager.GetObject("bab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bab1 {
            get {
                object obj = ResourceManager.GetObject("bab1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000025861f9812e0e7f538376bd {
            get {
                object obj = ResourceManager.GetObject("file_00000000025861f9812e0e7f538376bd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000046c61f8b4b8ef1e69a93558 {
            get {
                object obj = ResourceManager.GetObject("file_00000000046c61f8b4b8ef1e69a93558", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000046c61f8b4b8ef1e69a935581 {
            get {
                object obj = ResourceManager.GetObject("file_00000000046c61f8b4b8ef1e69a935581", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000000a0861f8a34572086b071e02 {
            get {
                object obj = ResourceManager.GetObject("file_000000000a0861f8a34572086b071e02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000000a0861f8a34572086b071e021 {
            get {
                object obj = ResourceManager.GetObject("file_000000000a0861f8a34572086b071e021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000000a0861f8a34572086b071e022 {
            get {
                object obj = ResourceManager.GetObject("file_000000000a0861f8a34572086b071e022", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000103861f98e8e2ae6bc090cd4 {
            get {
                object obj = ResourceManager.GetObject("file_00000000103861f98e8e2ae6bc090cd4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000107461fd89584c6372a26d93 {
            get {
                object obj = ResourceManager.GetObject("file_00000000107461fd89584c6372a26d93", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000107461fd89584c6372a26d931 {
            get {
                object obj = ResourceManager.GetObject("file_00000000107461fd89584c6372a26d931", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000150061f5a9bf642047b857dd {
            get {
                object obj = ResourceManager.GetObject("file_00000000150061f5a9bf642047b857dd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000150061f5a9bf642047b857dd1 {
            get {
                object obj = ResourceManager.GetObject("file_00000000150061f5a9bf642047b857dd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000001e2c620a9d70cef6783a00b4 {
            get {
                object obj = ResourceManager.GetObject("file_000000001e2c620a9d70cef6783a00b4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000002418622f99213b0a2799fbc1 {
            get {
                object obj = ResourceManager.GetObject("file_000000002418622f99213b0a2799fbc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000255861f892939bfd2de8a940 {
            get {
                object obj = ResourceManager.GetObject("file_00000000255861f892939bfd2de8a940", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000002c9061f9b54e2ae5b3dfe439 {
            get {
                object obj = ResourceManager.GetObject("file_000000002c9061f9b54e2ae5b3dfe439", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000002ca061f885c116b8b6b60385 {
            get {
                object obj = ResourceManager.GetObject("file_000000002ca061f885c116b8b6b60385", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000002ca061f885c116b8b6b603851 {
            get {
                object obj = ResourceManager.GetObject("file_000000002ca061f885c116b8b6b603851", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000002ca061f885c116b8b6b6038510 {
            get {
                object obj = ResourceManager.GetObject("file_000000002ca061f885c116b8b6b6038510", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000002ca061f885c116b8b6b603852 {
            get {
                object obj = ResourceManager.GetObject("file_000000002ca061f885c116b8b6b603852", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000002ca061f885c116b8b6b603853 {
            get {
                object obj = ResourceManager.GetObject("file_000000002ca061f885c116b8b6b603853", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000002ca061f885c116b8b6b603854 {
            get {
                object obj = ResourceManager.GetObject("file_000000002ca061f885c116b8b6b603854", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000002ca061f885c116b8b6b603855 {
            get {
                object obj = ResourceManager.GetObject("file_000000002ca061f885c116b8b6b603855", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000002ca061f885c116b8b6b603856 {
            get {
                object obj = ResourceManager.GetObject("file_000000002ca061f885c116b8b6b603856", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000002ca061f885c116b8b6b603857 {
            get {
                object obj = ResourceManager.GetObject("file_000000002ca061f885c116b8b6b603857", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000002ca061f885c116b8b6b603858 {
            get {
                object obj = ResourceManager.GetObject("file_000000002ca061f885c116b8b6b603858", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000002ca061f885c116b8b6b603859 {
            get {
                object obj = ResourceManager.GetObject("file_000000002ca061f885c116b8b6b603859", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000002e5461f89dc240cc6fef944c {
            get {
                object obj = ResourceManager.GetObject("file_000000002e5461f89dc240cc6fef944c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000002e5461f89dc240cc6fef944c1 {
            get {
                object obj = ResourceManager.GetObject("file_000000002e5461f89dc240cc6fef944c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000030b061f6a7899cf3c8664932 {
            get {
                object obj = ResourceManager.GetObject("file_0000000030b061f6a7899cf3c8664932", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000036a861f79b8eafdae41bf8d3__1_ {
            get {
                object obj = ResourceManager.GetObject("file_0000000036a861f79b8eafdae41bf8d3 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000036d461fdbe609c19c54ab86a {
            get {
                object obj = ResourceManager.GetObject("file_0000000036d461fdbe609c19c54ab86a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000036d461fdbe609c19c54ab86a1 {
            get {
                object obj = ResourceManager.GetObject("file_0000000036d461fdbe609c19c54ab86a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000378061f780e3f922682ea756 {
            get {
                object obj = ResourceManager.GetObject("file_00000000378061f780e3f922682ea756", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000038806246a180dfc950879b90 {
            get {
                object obj = ResourceManager.GetObject("file_0000000038806246a180dfc950879b90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000395061f7a78932deeed16240 {
            get {
                object obj = ResourceManager.GetObject("file_00000000395061f7a78932deeed16240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000395061f7a78932deeed162401 {
            get {
                object obj = ResourceManager.GetObject("file_00000000395061f7a78932deeed162401", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000396861f7a17d10cdbb5cf8b5 {
            get {
                object obj = ResourceManager.GetObject("file_00000000396861f7a17d10cdbb5cf8b5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000396861f7a17d10cdbb5cf8b51 {
            get {
                object obj = ResourceManager.GetObject("file_00000000396861f7a17d10cdbb5cf8b51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000396861f7a17d10cdbb5cf8b52 {
            get {
                object obj = ResourceManager.GetObject("file_00000000396861f7a17d10cdbb5cf8b52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000039fc61f7940ddd5fd2c28ce3 {
            get {
                object obj = ResourceManager.GetObject("file_0000000039fc61f7940ddd5fd2c28ce3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000039fc61f7940ddd5fd2c28ce31 {
            get {
                object obj = ResourceManager.GetObject("file_0000000039fc61f7940ddd5fd2c28ce31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000039fc61f7940ddd5fd2c28ce32 {
            get {
                object obj = ResourceManager.GetObject("file_0000000039fc61f7940ddd5fd2c28ce32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000041c061f88a72960545dd7f20 {
            get {
                object obj = ResourceManager.GetObject("file_0000000041c061f88a72960545dd7f20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000041c061f88a72960545dd7f201 {
            get {
                object obj = ResourceManager.GetObject("file_0000000041c061f88a72960545dd7f201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000041e8622fa748a7fe1c1988bf {
            get {
                object obj = ResourceManager.GetObject("file_0000000041e8622fa748a7fe1c1988bf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000420861f9a9a61a62283126ea {
            get {
                object obj = ResourceManager.GetObject("file_00000000420861f9a9a61a62283126ea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000465461f78f18b7281be5b74c__1_ {
            get {
                object obj = ResourceManager.GetObject("file_00000000465461f78f18b7281be5b74c (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000004b5c62438f2f5eb8e770979c {
            get {
                object obj = ResourceManager.GetObject("file_000000004b5c62438f2f5eb8e770979c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000004b5c62438f2f5eb8e770979c1 {
            get {
                object obj = ResourceManager.GetObject("file_000000004b5c62438f2f5eb8e770979c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000004b8861f5995745a69ce2ef02 {
            get {
                object obj = ResourceManager.GetObject("file_000000004b8861f5995745a69ce2ef02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000004b8861f5995745a69ce2ef021 {
            get {
                object obj = ResourceManager.GetObject("file_000000004b8861f5995745a69ce2ef021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000004b8861f5995745a69ce2ef022 {
            get {
                object obj = ResourceManager.GetObject("file_000000004b8861f5995745a69ce2ef022", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000004e0061f5a31ecbc2cb1dcc7f {
            get {
                object obj = ResourceManager.GetObject("file_000000004e0061f5a31ecbc2cb1dcc7f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000004e0061f5a31ecbc2cb1dcc7f1 {
            get {
                object obj = ResourceManager.GetObject("file_000000004e0061f5a31ecbc2cb1dcc7f1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000004e0061f5a31ecbc2cb1dcc7f2 {
            get {
                object obj = ResourceManager.GetObject("file_000000004e0061f5a31ecbc2cb1dcc7f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000005688622f9e4f23fe76473080 {
            get {
                object obj = ResourceManager.GetObject("file_000000005688622f9e4f23fe76473080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000583461fd99db974b580cb79f {
            get {
                object obj = ResourceManager.GetObject("file_00000000583461fd99db974b580cb79f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000005a7c61f8985ba3977f87220c {
            get {
                object obj = ResourceManager.GetObject("file_000000005a7c61f8985ba3977f87220c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000005a7c61f8985ba3977f87220c1 {
            get {
                object obj = ResourceManager.GetObject("file_000000005a7c61f8985ba3977f87220c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000005a7c61f8985ba3977f87220c2 {
            get {
                object obj = ResourceManager.GetObject("file_000000005a7c61f8985ba3977f87220c2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000633061f89467479b7e0d199e {
            get {
                object obj = ResourceManager.GetObject("file_00000000633061f89467479b7e0d199e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000633061f89467479b7e0d199e1 {
            get {
                object obj = ResourceManager.GetObject("file_00000000633061f89467479b7e0d199e1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000067b061fd8d36a83d02fbce2c {
            get {
                object obj = ResourceManager.GetObject("file_0000000067b061fd8d36a83d02fbce2c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000067b061fd8d36a83d02fbce2c1 {
            get {
                object obj = ResourceManager.GetObject("file_0000000067b061fd8d36a83d02fbce2c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000006bd86230b50db6cf2f30536f__1_ {
            get {
                object obj = ResourceManager.GetObject("file_000000006bd86230b50db6cf2f30536f (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000723c61f8b13b21e82df56227 {
            get {
                object obj = ResourceManager.GetObject("file_00000000723c61f8b13b21e82df56227", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000073986230bbe83e46a8f64303 {
            get {
                object obj = ResourceManager.GetObject("file_0000000073986230bbe83e46a8f64303", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000074e061f885bfef7212e70fb0 {
            get {
                object obj = ResourceManager.GetObject("file_0000000074e061f885bfef7212e70fb0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000074e061f885bfef7212e70fb01 {
            get {
                object obj = ResourceManager.GetObject("file_0000000074e061f885bfef7212e70fb01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000764461f8aa7f131001997564 {
            get {
                object obj = ResourceManager.GetObject("file_00000000764461f8aa7f131001997564", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000007a3061f7bc026e5cbbc05b25 {
            get {
                object obj = ResourceManager.GetObject("file_000000007a3061f7bc026e5cbbc05b25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000007cf461f4ae27cad0368d743d {
            get {
                object obj = ResourceManager.GetObject("file_000000007cf461f4ae27cad0368d743d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000007cf461f4ae27cad0368d743d1 {
            get {
                object obj = ResourceManager.GetObject("file_000000007cf461f4ae27cad0368d743d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000879061f59a754de92d1c1b2c {
            get {
                object obj = ResourceManager.GetObject("file_00000000879061f59a754de92d1c1b2c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000881061f7bcab14edebc85cac {
            get {
                object obj = ResourceManager.GetObject("file_00000000881061f7bcab14edebc85cac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000881061f7bcab14edebc85cac1 {
            get {
                object obj = ResourceManager.GetObject("file_00000000881061f7bcab14edebc85cac1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000008cf8622f8073380be536df5d {
            get {
                object obj = ResourceManager.GetObject("file_000000008cf8622f8073380be536df5d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000957c61f5b56a37d10d64d6d7 {
            get {
                object obj = ResourceManager.GetObject("file_00000000957c61f5b56a37d10d64d6d7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000957c61f5b56a37d10d64d6d71 {
            get {
                object obj = ResourceManager.GetObject("file_00000000957c61f5b56a37d10d64d6d71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000957c61f5b56a37d10d64d6d72 {
            get {
                object obj = ResourceManager.GetObject("file_00000000957c61f5b56a37d10d64d6d72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000957c61f5b56a37d10d64d6d73 {
            get {
                object obj = ResourceManager.GetObject("file_00000000957c61f5b56a37d10d64d6d73", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000096c061f8afc66d7068585491 {
            get {
                object obj = ResourceManager.GetObject("file_0000000096c061f8afc66d7068585491", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000096d46246b7d70f5806225bb1 {
            get {
                object obj = ResourceManager.GetObject("file_0000000096d46246b7d70f5806225bb1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_0000000096d46246b7d70f5806225bb11 {
            get {
                object obj = ResourceManager.GetObject("file_0000000096d46246b7d70f5806225bb11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000009a2461f8b6644034c8cb31a1 {
            get {
                object obj = ResourceManager.GetObject("file_000000009a2461f8b6644034c8cb31a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000009a2461f8b6644034c8cb31a11 {
            get {
                object obj = ResourceManager.GetObject("file_000000009a2461f8b6644034c8cb31a11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_000000009f9461f490aaa37391ebc846 {
            get {
                object obj = ResourceManager.GetObject("file_000000009f9461f490aaa37391ebc846", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000a40862309a7cca462f569180 {
            get {
                object obj = ResourceManager.GetObject("file_00000000a40862309a7cca462f569180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000a43461f4be6deecd068d2c73 {
            get {
                object obj = ResourceManager.GetObject("file_00000000a43461f4be6deecd068d2c73", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000a43461f4be6deecd068d2c731 {
            get {
                object obj = ResourceManager.GetObject("file_00000000a43461f4be6deecd068d2c731", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000aa006246b006e31e7df7be2e {
            get {
                object obj = ResourceManager.GetObject("file_00000000aa006246b006e31e7df7be2e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000aa006246b006e31e7df7be2e1 {
            get {
                object obj = ResourceManager.GetObject("file_00000000aa006246b006e31e7df7be2e1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000aa1861f580d7b96789f519ac {
            get {
                object obj = ResourceManager.GetObject("file_00000000aa1861f580d7b96789f519ac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000aa1861f580d7b96789f519ac1 {
            get {
                object obj = ResourceManager.GetObject("file_00000000aa1861f580d7b96789f519ac1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000abec61f9bc222c09d03c8a98 {
            get {
                object obj = ResourceManager.GetObject("file_00000000abec61f9bc222c09d03c8a98", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000ad7c61fd815983645319ab42 {
            get {
                object obj = ResourceManager.GetObject("file_00000000ad7c61fd815983645319ab42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000ad7c61fd815983645319ab421 {
            get {
                object obj = ResourceManager.GetObject("file_00000000ad7c61fd815983645319ab421", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000ae1861f7acc2b6af28ed6789 {
            get {
                object obj = ResourceManager.GetObject("file_00000000ae1861f7acc2b6af28ed6789", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000ae1861f7acc2b6af28ed67891 {
            get {
                object obj = ResourceManager.GetObject("file_00000000ae1861f7acc2b6af28ed67891", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000b25462468260b107da5b2a27 {
            get {
                object obj = ResourceManager.GetObject("file_00000000b25462468260b107da5b2a27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000b540622fa6f2d2fec6cf7a2d {
            get {
                object obj = ResourceManager.GetObject("file_00000000b540622fa6f2d2fec6cf7a2d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000b57c61f8bdd5a7fc77ab957e {
            get {
                object obj = ResourceManager.GetObject("file_00000000b57c61f8bdd5a7fc77ab957e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000becc622f91531a959c2af78d {
            get {
                object obj = ResourceManager.GetObject("file_00000000becc622f91531a959c2af78d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000c08861f88df53139aa982027 {
            get {
                object obj = ResourceManager.GetObject("file_00000000c08861f88df53139aa982027", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000c8f461f79f175293eba14da4 {
            get {
                object obj = ResourceManager.GetObject("file_00000000c8f461f79f175293eba14da4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000cdd861f89701226bf009197f {
            get {
                object obj = ResourceManager.GetObject("file_00000000cdd861f89701226bf009197f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000cdd862468188c8d7ff9bbb3e {
            get {
                object obj = ResourceManager.GetObject("file_00000000cdd862468188c8d7ff9bbb3e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000cfac61f7a25d6d862a2d18e3__1_ {
            get {
                object obj = ResourceManager.GetObject("file_00000000cfac61f7a25d6d862a2d18e3 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000d65c61fdb1a2df461e9256b3 {
            get {
                object obj = ResourceManager.GetObject("file_00000000d65c61fdb1a2df461e9256b3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000d65c61fdb1a2df461e9256b31 {
            get {
                object obj = ResourceManager.GetObject("file_00000000d65c61fdb1a2df461e9256b31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000d65c61fdb1a2df461e9256b32 {
            get {
                object obj = ResourceManager.GetObject("file_00000000d65c61fdb1a2df461e9256b32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000dbdc61f8bfac5700ec5907d8 {
            get {
                object obj = ResourceManager.GetObject("file_00000000dbdc61f8bfac5700ec5907d8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000dbdc61f8bfac5700ec5907d81 {
            get {
                object obj = ResourceManager.GetObject("file_00000000dbdc61f8bfac5700ec5907d81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000dc0861f5bfe476ac40fd1df7 {
            get {
                object obj = ResourceManager.GetObject("file_00000000dc0861f5bfe476ac40fd1df7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000dc0861f5bfe476ac40fd1df71 {
            get {
                object obj = ResourceManager.GetObject("file_00000000dc0861f5bfe476ac40fd1df71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000e96861f8bf1045b9a9dfcd7b {
            get {
                object obj = ResourceManager.GetObject("file_00000000e96861f8bf1045b9a9dfcd7b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000f1286230a3b9b0a3198033a0 {
            get {
                object obj = ResourceManager.GetObject("file_00000000f1286230a3b9b0a3198033a0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000f37461f7b3c81ce78e426978 {
            get {
                object obj = ResourceManager.GetObject("file_00000000f37461f7b3c81ce78e426978", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000f37461f7b3c81ce78e4269781 {
            get {
                object obj = ResourceManager.GetObject("file_00000000f37461f7b3c81ce78e4269781", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_00000000f3d0624383f629cb5bc78afe {
            get {
                object obj = ResourceManager.GetObject("file_00000000f3d0624383f629cb5bc78afe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_20250525_163928_673 {
            get {
                object obj = ResourceManager.GetObject("IMG_20250525_163928_673", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_20250525_163928_6731 {
            get {
                object obj = ResourceManager.GetObject("IMG_20250525_163928_6731", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ov {
            get {
                object obj = ResourceManager.GetObject("ov", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Presentation1 {
            get {
                object obj = ResourceManager.GetObject("Presentation1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
